In [2]:
%matplotlib notebook
import csv
from scipy.io import loadmat
import numpy as np
import scipy.optimize as opt
from pandas.io.parsers import read_csv
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
from matplotlib import cm
from matplotlib.ticker import LinearLocator, FormatStrFormatter
from sklearn.preprocessing import PolynomialFeatures

In [66]:
data = loadmat('ex5data1.mat')
y = data['y']
x = data['X']
yval = data['yval']
xval = data['Xval']
ytest = data['ytest']
xtest = data['Xtest']
th = np.ones((2,1))
x = np.insert(x,0,np.ones(len(x)),axis=1)

In [68]:
np.dot(x,th)[:,0]
x

array([[  1.        , -15.93675813],
       [  1.        , -29.15297922],
       [  1.        ,  36.18954863],
       [  1.        ,  37.49218733],
       [  1.        , -48.05882945],
       [  1.        ,  -8.94145794],
       [  1.        ,  15.30779289],
       [  1.        , -34.70626581],
       [  1.        ,   1.38915437],
       [  1.        , -44.38375985],
       [  1.        ,   7.01350208],
       [  1.        ,  22.76274892]])

In [70]:
def coste(th,x,y,reg = 1):
    m = x.shape[0]
    return (1/(2*m)) * np.sum(np.square(np.dot(x,th) - y)) + (reg/(2*m)) * np.sum(np.square(th[1:])) 

coste(th,x,y)

303.9931922202643

In [412]:
def gradiente(th,x,y,reg=0):
    t0 = np.sum((np.ravel(np.dot(x, th)-y)) * x[:,0])/len(x)
    t1 = np.sum((np.dot(x, th)-y) * x[:,1:])/len(x) + reg * np.ravel(th[1:])/len(x)
    return np.append(t0,t1)

In [413]:
gradiente(th,x,y)

array([-15.30301567, 598.16741084])

In [408]:
(np.dot(x, th)-y)[1:]

array([[-29.3262359 ],
       [  2.83043945],
       [  1.65423217],
       [-49.86779453],
       [-10.06253041],
       [  1.59752458],
       [-36.3204502 ],
       [ -1.3510173 ],
       [-47.11545116],
       [  0.38584323],
       [  1.01032062]])

In [219]:
np.sum(np.multiply((np.ravelnp.dot(x, th)-y)), x[0,1]))/len(x)

22.671457667428143

In [389]:
np.multiply((np.dot(x, th)-y),x[:,0])

array([[-17.07106864, -17.07106864, -17.07106864, -17.07106864,
        -17.07106864, -17.07106864, -17.07106864, -17.07106864,
        -17.07106864, -17.07106864, -17.07106864, -17.07106864],
       [-29.3262359 , -29.3262359 , -29.3262359 , -29.3262359 ,
        -29.3262359 , -29.3262359 , -29.3262359 , -29.3262359 ,
        -29.3262359 , -29.3262359 , -29.3262359 , -29.3262359 ],
       [  2.83043945,   2.83043945,   2.83043945,   2.83043945,
          2.83043945,   2.83043945,   2.83043945,   2.83043945,
          2.83043945,   2.83043945,   2.83043945,   2.83043945],
       [  1.65423217,   1.65423217,   1.65423217,   1.65423217,
          1.65423217,   1.65423217,   1.65423217,   1.65423217,
          1.65423217,   1.65423217,   1.65423217,   1.65423217],
       [-49.86779453, -49.86779453, -49.86779453, -49.86779453,
        -49.86779453, -49.86779453, -49.86779453, -49.86779453,
        -49.86779453, -49.86779453, -49.86779453, -49.86779453],
       [-10.06253041, -10.06253041,

In [399]:
(np.dot(x, th)-y).shape

(12, 1)

In [391]:
x[:,0].shape

(12,)

In [401]:
x[:,1:].shape

(12, 1)

In [173]:
x[:,1]

array([-15.93675813, -29.15297922,  36.18954863,  37.49218733,
       -48.05882945,  -8.94145794,  15.30779289, -34.70626581,
         1.38915437, -44.38375985,   7.01350208,  22.76274892])